Fix hooks

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -33,13 +33,6 @@ function init_db {
 	if fgrep -q "0" $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB
 	then
 
-	# Add OPENSHIFT_MARIADB_VERSION variable to help mysql_context
-	# choose the right version. Also need to be exported for install.
-	env_dir="${OPENSHIFT_MARIADB_DIR}/env"
-	set_env_var 'OPENSHIFT_MARIADB_VERSION' $version $env_dir
-	export OPENSHIFT_MARIADB_VERSION=$version
-
-
 	## 
 	#
 	# Starting the galera cluster is a three step process:
@@ -95,15 +88,18 @@ function init_db {
 	username=$OPENSHIFT_MARIADB_DB_USERNAME
 	password=$OPENSHIFT_MARIADB_DB_PASSWORD
 
+	# We MUST run mysql from this dir or else it will fail
+        cd $OPENSHIFT_MARIADB_DIR/binaries/mariadb
+
 	# Drop the test database and create our application's database
 	echo "drop database test;
-	create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
+	create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "./bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
 
 	# Delete the test user and create our admin user from the generated_username and generated_password
 	echo "                                  
 	delete from user;
 	grant all on *.* to '$username'@'%' identified by '$password' with grant option;
-	flush privileges;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
+	flush privileges;" | mysql_context "./bin/mysql -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
 
 echo "control=$OPENSHIFT_GEAR_DNS - has finished db-init" 
 
@@ -131,6 +127,11 @@ then
     echo "control=$OPENSHIFT_GEAR_DNS - active_gears=$active_gears" 
     for i in ${active_gears[@]}; 
     do 
+	# Ignore own host
+	if [ "$OPENSHIFT_GEAR_DNS:$OPENSHIFT_MARIADB_NODE_GALERA_PORT_1" == $i ] 
+	then
+		continue
+	fi
 	# test if host is accessible (nc not available)
 	# if nc -w 5 $(echo $i | tr ":" "\n") 2>/dev/null
 	echo "quit" | telnet $(echo $i | tr ":" "\n") | grep Connected > /dev/null 2>&1
@@ -147,7 +148,7 @@ then
     # We MUST run mysqld_safe from this dir or else it will fail
     cd $OPENSHIFT_MARIADB_DIR/binaries/mariadb
     
-    # Generate the dynamic wsrep_cluster_addresses (none prints out as 1 - so we want at least 3 which means 2 are online)
+    # Generate the dynamic wsrep_cluster_addresses (none prints out as 1 - so we ideally want at least 3 which means 2 are online)
     if [ `echo $online_gears | sed 's/[^,]//g' | wc -c` -gt 2 ];
     then
     	# Adding more hosts to the cluster
