Fix logic

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -49,7 +49,7 @@ function init_db {
 	# We MUST run mysql from this dir or else it will fail
         cd $OPENSHIFT_MARIADB_DIR/usr/mariadb
 	
-	# Start MariaDB (standalone) - mysqld_safe doesn't seem to like non-galera startup
+	# Start MariaDB (standalone)
 	./bin/mysqld --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf > /dev/null 2>&1 &
 
 	# Wait for MariaDB to Start
@@ -62,11 +62,11 @@ function init_db {
 	# Delete the test user and create our admin user from the generated_username and generated_password
 	echo "                                  
 	delete from user;
-	grant all on *.* to '$username'@'%' identified by '$password' with grant option;" | ./bin/mysql -u root -S ${socket_file} mysql > /dev/null || error "Failed to setup initial root user" 187
+	grant all on *.* to '$username'@'%' identified by '$password' with grant option; flush privileges;" | ./bin/mysql -u root -S ${socket_file} mysql > /dev/null || error "Failed to setup initial root user" 187
 
 	# Create haproxy user for the alive check
 	echo "
-	GRANT ALL ON *.* to 'haproxy'@'%' IDENTIFIED BY ''; flush privileges;" | ./bin/mysql -u root -S ${socket_file} mysql > /dev/null || error "Failed to create haproxy user" 187
+	GRANT ALL ON *.* to 'haproxy'@'%' IDENTIFIED BY ''; " | ./bin/mysql -u $username -p$password -S ${socket_file} mysql > /dev/null || error "Failed to create haproxy user" 187
 
 	# This should touch as root, which should prevent any future snoopy human mistakes
 	touch $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_DB_INIT
