localhost

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -108,8 +108,11 @@ password='pass'
 	# Delete the test user and create our admin user from the generated_username and generated_password
 	echo "                                  
 	delete from user;
-	grant all on *.* to '$username'@'%' identified by '$password' with grant option;
+	grant all on *.* to '$username'@'%' identified by '$password' with grant option; grant all on *.* to '$username'@'localhost' identified by '$password' with grant option;
 	flush privileges;" | ./bin/mysql -u root -S ${socket_file} mysql > /dev/null || error "Failed to setup initial root user" 187
+
+	# Delete the test user and create our admin user from the generated_username and generated_password
+	echo "flush privileges;" | ./bin/mysql -u root -S ${socket_file} mysql > /dev/null || error "Failed to setup initial root user" 187
 
 	# DB-INIT Complete
 	echo "1" > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB
