test

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -63,11 +63,11 @@ password='pass'
 
 	echo 'Bootstrap MariaDB'
 
-	# Setup the my-cnf Files
-	oo-erb $OPENSHIFT_MARIADB_DIR/conf/my.cnf.erb.hidden > $OPENSHIFT_MARIADB_DIR/conf/my.cnf
+	# Setup the my-cnf init file
+	oo-erb $OPENSHIFT_MARIADB_DIR/conf/my-init.cnf.erb.hidden > $OPENSHIFT_MARIADB_DIR/conf/my.cnf
 
 	# Initialize the MariaDB databases - basedir is IMPORTANT!
-	#$OPENSHIFT_MARIADB_DIR/binaries/mariadb/scripts/mysql_install_db --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf --basedir=$OPENSHIFT_MARIADB_DIR/binaries/mariadb/ --datadir=$OPENSHIFT_MARIADB_DIR/data --user=$USER || error 'Failed to create mariadb database', 119
+	$OPENSHIFT_MARIADB_DIR/binaries/mariadb/scripts/mysql_install_db --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf --basedir=$OPENSHIFT_MARIADB_DIR/binaries/mariadb/ --datadir=$OPENSHIFT_MARIADB_DIR/data --user=$USER || error 'Failed to create mariadb database', 119
 
 	client_result ""
 	client_result "MariaDB Galera Cluster ${OPENSHIFT_MARIADB_VERSION} database added.  Please make note of these credentials:"
@@ -95,21 +95,21 @@ password='pass'
 	# We MUST run mysql from this dir or else it will fail
         cd $OPENSHIFT_MARIADB_DIR/binaries/mariadb
 	
-	# Start MariaDB (standalone)
-	#./bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf > /dev/null 2>&1 &
+	# Start MariaDB (standalone) - mysqld_safe doesn't seem to like non-galera startup
+	./bin/mysqld --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf > /dev/null 2>&1 &
 
 	# Wait for MariaDB to Start
 	sleep 15
 
 	# Drop the test database and create our application's database
-	#echo "drop database test;
-	#create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | ./bin/mysql -u root -S ${socket_file} > /dev/null || error 'Failed to create database' 188
+	echo "drop database test;
+	create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | ./bin/mysql -u root -S ${socket_file} > /dev/null || error 'Failed to create database' 188
 
 	# Delete the test user and create our admin user from the generated_username and generated_password
-	#echo "                                  
-	#delete from user;
-	#grant all on *.* to '$username'@'%' identified by '$password' with grant option;
-	#flush privileges;" | ./bin/mysql -u root -S ${socket_file} mysql > /dev/null || error "Failed to setup initial root user" 187
+	echo "                                  
+	delete from user;
+	grant all on *.* to '$username'@'%' identified by '$password' with grant option;
+	flush privileges;" | ./bin/mysql -u root -S ${socket_file} mysql > /dev/null || error "Failed to setup initial root user" 187
 
 	# DB-INIT Complete
 	echo "1" > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_INIT_DB
