refractor

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -58,13 +58,13 @@ mysql_context "./bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.
 
 # Clean Up
 echo "drop database test;
-create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
+create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
 
 # Create New User
 echo "                                  
 delete from user;
 grant all on *.* to '$username'@'%' identified by '$password' with grant option;
-flush privileges;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
+flush privileges;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
 
 # Give it some time to settle in
 sleep 5
