refractor

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -10,15 +10,25 @@ esac
 
 # Add OPENSHIFT_MARIADB_VERSION variable to help mysql_context
 # choose the right version. Also need to be exported for install.
-#
 env_dir="${OPENSHIFT_MARIADB_DIR}/env"
 set_env_var 'OPENSHIFT_MARIADB_VERSION' $version $env_dir
 export OPENSHIFT_MARIADB_VERSION=$version
 
+
+## 
+#
+# Starting the galera cluster is a three step process:
+#   1. Start first node and use mysql_install_db
+#   2. Restart the first node to initiate the galera cluster
+#   3. Join the other hosts to the cluster
+#
+##
+
 # Check if this is the first host in cluster
+# This method won't work.. 
 #if [ `wc -l $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MARIADB_NODE_GEARS | cut -f1 -d" "` -lt 2 ]
 #then
-	
+
 # Generate username, password, and db name and create env variables
 echo 'Generating username and password'
 
@@ -34,12 +44,40 @@ echo "$username" > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MYSQL_DB_USERNAME
 echo "$password" > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MYSQL_DB_PASSWORD
 echo "mysql://$username:$password@$OPENSHIFT_MARIADB_DB_HOST:$OPENSHIFT_MARIADB_DB_PORT/" > $OPENSHIFT_MARIADB_DIR/env/OPENSHIFT_MYSQL_DB_URL
 
-echo 'Installing mariadb'
+echo 'Bootstrap MariaDB'
 
-mariadb_data_dir="${OPENSHIFT_MARIADB_DIR}/data"
+# Setup the my-cnf Files
+oo-erb $OPENSHIFT_MARIADB_DIR/conf/my-init.cnf.erb.hidden > $OPENSHIFT_MARIADB_DIR/conf/my.cnf
 
-# basedir is important because we're using the downloaded binary
-mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/scripts/mysql_install_db --basedir=$OPENSHIFT_MARIADB_DIR/binaries/mariadb/ --datadir=${mariadb_data_dir} --user=${USER}" || error 'Failed to create mariadb database', 119
+# Initialize the MariaDB databases - basedir is IMPORTANT!
+mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/scripts/mysql_install_db --basedir=$OPENSHIFT_MARIADB_DIR/binaries/mariadb/ --datadir=${OPENSHIFT_MARIADB_DIR}/data --user=${USER}" || error 'Failed to create mariadb database', 119
+
+# Starting MariaDB in Standalone Mode
+echo 'Starting MariaDB in standalone mode'
+mysql_context "./bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf" > /dev/null 2>&1 &
+
+# Clean Up
+echo "drop database test;
+create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
+
+# Create New User
+echo "                                  
+delete from user;
+grant all on *.* to '$username'@'%' identified by '$password' with grant option;
+flush privileges;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
+
+# Give it some time to settle in
+sleep 5
+
+# Bring down MariaDB
+echo 'Shutting down MariaDB to prepare for galera gluster'
+$OPENSHIFT_MARIADB_DIR/bin/control stop
+
+# Setup the new my-cnf Files
+oo-erb $OPENSHIFT_MARIADB_DIR/conf/my-cluster.cnf.erb.hidden > $OPENSHIFT_MARIADB_DIR/conf/my.cnf
+
+## Now Start the new_cluster
+mysql_context "./bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf --wsrep_node_address="$OPENSHIFT_GEAR_DNS" --wsrep_node_incoming_address="$OPENSHIFT_GEAR_DNS" --wsrep_new_cluster --wsrep_cluster_address='gcomm://' " > /dev/null 2>&1 &
 
 client_result ""
 client_result "MariaDB Galera Cluster ${OPENSHIFT_MARIADB_VERSION} database added.  Please make note of these credentials:"
@@ -59,25 +97,3 @@ cart_props "username=$username"
 cart_props "password=$password"
 cart_props "database_name=$OPENSHIFT_APP_NAME"
 
-
-## Now Start the new_cluster
-mysql_context "./bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf --wsrep_node_address="$OPENSHIFT_GEAR_DNS" --wsrep_node_incoming_address="$OPENSHIFT_GEAR_DNS" --wsrep_new_cluster --wsrep_cluster_address='gcomm://' " > /dev/null 2>&1 &
-
-## Clean Up
-echo "drop database test;
-create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
-
-echo "                                  
-delete from user;
-grant all on *.* to '$username'@'$OPENSHIFT_MARIADB_DB_HOST' identified by '$password' with grant option;
-grant all on *.* to '$username'@'%' identified by '$password' with grant option;
-flush privileges;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
-
-# Restart MariaDB
-$OPENSHIFT_MARIADB_DIR/bin/control restart
-
-#else
-#	# Join the cluster
-#	$OPENSHIFT_MARIADB_DIR/bin/control start
-#
-#fi
