refractor

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -57,7 +57,7 @@ mysql_context "./bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.
 
 # Clean Up
 echo "drop database test;
-create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$OPENSHIFT_MARIADB_DB_SOCKET'" > /dev/null || error 'Failed to create database' 188
+create database '$OPENSHIFT_APP_NAME' DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/binaries/mariadb/bin/mysql -u root -S '$OPENSHIFT_MARIADB_DB_SOCKET'" > /dev/null || error 'Failed to create database' 188
 
 # Create New User
 echo "                                  
