Some areas were using wrong binary file

diff --git a/bin/post_install b/bin/post_install
--- a/bin/post_install
+++ b/bin/post_install
@@ -13,13 +13,13 @@ password=$OPENSHIFT_MARIADB_DB_PASSWORD
 # TODO: Should be we running mysql_secure_installation
 
 echo "drop database test;
-create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "/usr/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
+create database \`${dbname}\` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;" | mysql_context "$OPENSHIFT_MARIADB_DIR/mariadb/bin/mysql -u root -S '$socket_file'" > /dev/null || error 'Failed to create database' 188
 
 echo "                                  
 delete from user;
 grant all on *.* to '$username'@'$OPENSHIFT_MARIADB_DB_HOST' identified by '$password' with grant option;
 grant all on *.* to '$username'@'%' identified by '$password' with grant option;
-flush privileges;" | mysql_context "/usr/bin/mysql -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
+flush privileges;" | mysql_context "$OPENSHIFT_MARIADB_DIR/mariadb/bin/mysql -u root -S '$socket_file' mysql" > /dev/null || error "Failed to setup initial root user" 187
 
 
 # Now that we've created the initial database, we restart it as part of the cluster (not sure if this'll work..)
@@ -41,4 +41,4 @@ if [ -f $pidfile ]; then
 fi      
 
 # We run this wsrep_new_cluster only ONCE
-mysql_context "/usr/bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf" --wsrep_node_address="${OPENSHIFT_GEAR_DNS}" --wsrep_node_incoming_address="${OPENSHIFT_GEAR_DNS}" --wsrep_new_cluster --wsrep_cluster_address="gcomm://" > /dev/null 2>&1 &
+mysql_context "$OPENSHIFT_MARIADB_DIR/mariadb/bin/mysqld_safe --defaults-file=$OPENSHIFT_MARIADB_DIR/conf/my.cnf" --wsrep_node_address="${OPENSHIFT_GEAR_DNS}" --wsrep_node_incoming_address="${OPENSHIFT_GEAR_DNS}" --wsrep_new_cluster --wsrep_cluster_address="gcomm://" > /dev/null 2>&1 &
